apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: microservice
  name: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: microservice
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/microservice-net: "true"
        io.kompose.service: microservice
    spec:
      containers:
        - env:
            - name: GET_HOST_FROM
              value: dns
          image: alpine
          name: microservice
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /go/src/microservice
              name: microservice-claim0
      hostname: microservice
      restartPolicy: Always
      volumes:
        - name: microservice-claim0
          persistentVolumeClaim:
            claimName: microservice-claim0
status: {}
