name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Add secrets
      run: |
        mkdir ~/.config/tbr/
        echo  ${{ secrets.POSTGRES_DB_CREDENTIALS }} > ~/.config/tbr/.postgres_credentials_test.env
    - name: Test
      run: |
        cd microservice
        go test ./...
